!EOC
!------------------------------------------------------------------------------
!                  GEOS-Chem Global Chemical Transport Model                  !
!------------------------------------------------------------------------------
!BOP
!
! !IROUTINE: read_from_netcdf_file
!
! !DESCRIPTION: Routine to read variables and attributes from a netCDF
!  file.  This routine was automatically generated by the Perl script
!  NcdfUtilities/perl/ncCodeRead.
!\\
!\\
! !INTERFACE:
!
      SUBROUTINE READ_FROM_NETCDF_FILE
!
! !USES:
!
      ! Modules for netCDF read
      USE m_netcdf_io_open
      USE m_netcdf_io_get_dimlen
      USE m_netcdf_io_read
      USE m_netcdf_io_readattr
      USE m_netcdf_io_close

      IMPLICIT NONE

#     include "netcdf.inc"
!
! !REMARKS:
!  Assumes that you have:
!  (1) A netCDF library (either v3 or v4) installed on your system
!  (2) The NcdfUtilities package (from Bob Yantosca) source code
!                                                                             .
!  Although this routine was generated automatically, some further
!  hand-editing may be required (i.e. to  specify the size of parameters, 
!  and/or to assign values to variables.  Also, you can decide how to handle
!  the variable attributes (or delete calls for reading attributes that you
!  do not need).
!
! !REVISION HISTORY:
!  30 Jan 2012 - R. Yantosca - Initial version
!EOP
!------------------------------------------------------------------------------
!BOC
!
! !LOCAL VARIABLES:
!
      INTEGER :: fId    ! netCDF file ID
      !=================================================================
      ! Variable declarations
      !=================================================================

      ! Data arrays
      REAL*4             :: lon(I_SOIL)
      REAL*4             :: lat(J_SOIL)
      REAL*4             :: THETA_WILT(I_SOIL,J_SOIL)
      REAL*4             :: THETA_CRIT(I_SOIL,J_SOIL)

      ! Character strings
      CHARACTER(LEN=255) :: nc_dir             ! netCDF directory name
      CHARACTER(LEN=255) :: nc_file            ! netCDF file name
      CHARACTER(LEN=255) :: nc_path            ! netCDF path name
      CHARACTER(LEN=255) :: v_name             ! netCDF variable name 
      CHARACTER(LEN=255) :: a_name             ! netCDF attribute name
      CHARACTER(LEN=255) :: a_val              ! netCDF attribute value

      ! Arrays for netCDF start and count values
      INTEGER            :: st1d(1), ct1d(1)   ! For 1D arrays    
      INTEGER            :: st2d(2), ct2d(2)   ! For 2D arrays 
      INTEGER            :: st3d(3), ct3d(3)   ! For 3D arrays 
      INTEGER            :: st4d(4), ct4d(4)   ! For 4D arrays 
      INTEGER            :: st5d(5), ct5d(5)   ! For 5D arrays 
      INTEGER            :: st6d(6), ct6d(6)   ! For 6D arrays 

      !=================================================================
      ! Open and read data from the netCDF file
      !=================================================================

      ! Open netCDF file
      nc_path = 'HadGEM2ES_Soil_Ancil.nc'
      CALL Ncop_Rd( fId, TRIM(nc_path) )

      ! Echo info to stdout
      nc_file = 'HadGEM2ES_Soil_Ancil.nc'  
      nc_dir  = '' 
      WRITE( 6, 100 ) REPEAT( '%', 79 )
      WRITE( 6, 110 ) TRIM(nc_file)
      WRITE( 6, 120 ) TRIM(nc_dir)

      !----------------------------------------
      ! VARIABLE: lon
      !----------------------------------------

      ! Variable name
      v_name = "lon"

      ! Read lon from file
      st1d   = (/ 1 /)
      ct1d   = (/ I_SOIL /)
      CALL NcRd( lon, fId, TRIM(v_name), st1d, ct1d )

      ! Read the lon:units attribute
      a_name = "units"
      CALL NcGet_Var_Attributes( fId,TRIM(v_name),TRIM(a_name),a_val )

      ! Echo info to stdout
      WRITE( 6, 130 ) TRIM(v_name), TRIM(a_val)

      !----------------------------------------
      ! VARIABLE: lat
      !----------------------------------------

      ! Variable name
      v_name = "lat"

      ! Read lat from file
      st1d   = (/ 1 /)
      ct1d   = (/ J_SOIL /)
      CALL NcRd( lat, fId, TRIM(v_name), st1d, ct1d )

      ! Read the lat:units attribute
      a_name = "units"
      CALL NcGet_Var_Attributes( fId,TRIM(v_name),TRIM(a_name),a_val )

      ! Echo info to stdout
      WRITE( 6, 130 ) TRIM(v_name), TRIM(a_val)

      !----------------------------------------
      ! VARIABLE: THETA_WILT
      !----------------------------------------

      ! Variable name
      v_name = "THETA_WILT"

      ! Read THETA_WILT from file
      st2d   = (/ 1, 1 /)
      ct2d   = (/ I_SOIL, J_SOIL /)
      CALL NcRd( THETA_WILT, fId, TRIM(v_name), st2d, ct2d )

      ! Read the THETA_WILT:units attribute
      a_name = "units"
      CALL NcGet_Var_Attributes( fId,TRIM(v_name),TRIM(a_name),a_val )

      ! Echo info to stdout
      WRITE( 6, 130 ) TRIM(v_name), TRIM(a_val)

      !----------------------------------------
      ! VARIABLE: THETA_CRIT
      !----------------------------------------

      ! Variable name
      v_name = "THETA_CRIT"

      ! Read THETA_CRIT from file
      st2d   = (/ 1, 1 /)
      ct2d   = (/ I_SOIL, J_SOIL /)
      CALL NcRd( THETA_CRIT, fId, TRIM(v_name), st2d, ct2d )

      ! Read the THETA_CRIT:units attribute
      a_name = "units"
      CALL NcGet_Var_Attributes( fId,TRIM(v_name),TRIM(a_name),a_val )

      ! Echo info to stdout
      WRITE( 6, 130 ) TRIM(v_name), TRIM(a_val)

      !=================================================================
      ! Cleanup and quit
      !=================================================================

      ! Close netCDF file
      CALL NcCl( fId )

      ! Echo info to stdout
      WRITE( 6, 140 )
      WRITE( 6, 100 ) REPEAT( '%', 79 )

      ! FORMAT statements
 100  FORMAT( a                                              )
 110  FORMAT( '%% Opening file  : ',         a               )
 120  FORMAT( '%%  in directory : ',         a, / , '%%'     )
 130  FORMAT( '%% Successfully read ',       a, ' [', a, ']' )
 140  FORMAT( '%% Successfully closed file!'                 )

      END SUBROUTINE READ_FROM_NETCDF_FILE
!EOC

